#ifndef _MISSING_2350_INCLUDE_H_
#define _MISSING_2350_INCLUDE_H_


#include "RP2350.h"
#include "pico/platform.h"

#include "hardware/structs/accessctrl.h"
#include "hardware/structs/adc.h"
#include "hardware/structs/bootram.h"
#include "hardware/structs/bus_ctrl.h"
#include "hardware/structs/clocks.h"
#include "hardware/structs/dma.h"
#include "hardware/structs/hstx_ctrl.h"
#include "hardware/structs/hstx_fifo.h"
#include "hardware/structs/i2c.h"
#include "hardware/structs/interp.h"
#include "hardware/structs/iobank0.h"
#include "hardware/structs/ioqspi.h"
#include "hardware/structs/m33_eppb.h"
#include "hardware/structs/m33.h"
#include "hardware/structs/mpu.h"
#include "hardware/structs/nvic.h"
#include "hardware/structs/otp.h"
#include "hardware/structs/padsbank0.h"
#include "hardware/structs/pads_qspi.h"
#include "hardware/structs/pio.h"
#include "hardware/structs/pll.h"
#include "hardware/structs/powman.h"
#include "hardware/structs/psm.h"
#include "hardware/structs/pwm.h"
#include "hardware/structs/qmi.h"
#include "hardware/structs/resets.h"
#include "hardware/structs/rosc.h"
#include "hardware/structs/sau.h"
#include "hardware/structs/scb.h"
#include "hardware/structs/sha256.h"
#include "hardware/structs/sio.h"
#include "hardware/structs/spi.h"
#include "hardware/structs/syscfg.h"
#include "hardware/structs/systick.h"
#include "hardware/structs/ticks.h"
#include "hardware/structs/timer.h"
#include "hardware/structs/tmds_encode.h"
#include "hardware/structs/trng.h"
#include "hardware/structs/uart.h"
#include "hardware/structs/usb.h"
#include "hardware/structs/watchdog.h"
#include "hardware/structs/xip_aux.h"
#include "hardware/structs/xip_ctrl.h"
#include "hardware/structs/xosc.h"


#endif

